version: "3"
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    shm_size: 2g
    ports:
      - 4444:4444
    volumes:
      - "./downloads:/home/seluser/Downloads"
    environment:
      DBUS_SESSION_BUS_ADDRESS: "/dev/null"
      VNC_NO_PASSWORD: "1"
    restart: unless-stopped

  vnc:
    image: dougw/novnc:latest
    ports:
      - 8081:8081
    environment:
      REMOTE_HOST: "selenium"
      REMOTE_PORT: "5900"
    restart: unless-stopped
